liste_sprite : &sprite_template
  vers_la_gauche : "images/poisson_vers_la_gauche.png"
  vers_la_droite : "images/poisson_vers_la_droite.png"


gupy : &poisson_template
  argent:
    argent_genere : 10
    periode_generation : 5
    curseur_generation : 0
  deplacement:
    inertie : 0
    inertie_max : 50
    velocite : 3
    direction : 
      droite : 
      - 1
      - 2
      - 3
      gauche : 
      - 5
      - 6
      - 7
  gestion_faim:
    faim_max : 30
    faim : 30
    seuil_appetance : 10.0
    valeur_nutritive : 60
  predation:
    est_proie : true
    est_predateur : false
    proies : 
    - ""
  affichage : &affichage_simple
    x : 300
    y : 300
    largeur : 60
    hauteur : 40
    liste_sprite_poisson : *sprite_template


piranha :
  << : *poisson_template
  predation : 
    est_proie : false 
    est_predateur : true
    proies : 
      - "gupy"
  affichage : 
    x : 100
    y : 100
    largeur : 60
    hauteur : 40 
    liste_sprite_poisson : 
      << : *sprite_template
      vers_la_gauche : "images/piranha_vers_la_gauche.png"
      vers_la_droite : "images/piranha_vers_la_droite.png"
  