fond_fenetre : &image_template
  chemin : "images/fond2.jpg"

liste_sprite : &sprite_template
  vers_la_gauche : "images/poisson_vers_la_gauche.png"
  vers_la_droite : "images/poisson_vers_la_droite.png"

aquarium : 
  vivants : 
    gupy : 10 
    piranha : 3
    # crevette : 3
    # meduse : 1
    # tortue : 2
    # sushi : 1
  affichage: 
    largeur_fenetre : 1000
    hauteur_fenetre : 600
    largeur_aquarium : 700
    hauteur_aquarium : 600
  boutons : 
    bouton_ajout_crevette : 1
    bouton_ajout_piranha : 1
    bouton_ajout_gupy : 1
    
bouton : &bouton_template
  x : 0
  y : 0
  largeur : 100
  hauteur : 48

boutons_ajout : 
  buton_ajout_gupy : 
    << : *bouton_template
    x : 710
    y : 542
    chemin_image : "images/poisson_vers_la_gauche.png"
    type_poisson : "gupy"
    type_bouton : "SpriteBouttonAjouter"


  buton_ajout_piranha : 
    << : *bouton_template
    x : 710
    y : 470
    chemin_image : "images/piranha_vers_la_gauche.png"
    type_poisson : "piranha"
    type_bouton : "SpriteBouttonAjouter"

  bouton_ajout_crevette : 
    << : *bouton_template
    x : 710
    y : 420
    chemin_image : "images/crevette_vers_la_gauche.png"
    type_poisson : "crevette"
    type_bouton : "SpriteBouttonAjouter"

  bouton_ajout_meduse : 
    << : *bouton_template
    x : 710
    y : 360
    chemin_image : "images/meduse_vers_la_gauche.png"
    type_poisson : "meduse"
    type_bouton : "SpriteBouttonAjouter"


  bouton_ajout_tortue : 
    << : *bouton_template
    x : 810
    y : 542
    chemin_image : "images/tortue_vers_la_gauche.png"
    type_poisson : "tortue"
    type_bouton : "SpriteBouttonAjouter"

  bouton_ajout_sushi : 
    << : *bouton_template
    x : 810
    y : 480
    chemin_image : "images/sushi.png"
    type_poisson : "sushi"
    type_bouton : "SpriteBouttonAjouter"

gupy : &poisson_template
  argent:
    argent_genere : 10
    periode_generation : 5
    curseur_generation : 0
  deplacement:
    inertie : 0
    inertie_max : 50
    velocite : 3
    direction : 
      droite : 
      - 1
      - 2
      - 3
      gauche : 
      - 5
      - 6
      - 7
  gestion_faim:
    faim_max : 100
    faim : 100
    seuil_appetance : 30.0
    valeur_nutritive : 30
  predation:
    est_proie : true
    est_predateur : false
    proies : 
    - ""
  affichage : &affichage_simple
    x : 300
    y : 300
    largeur : 60
    hauteur : 40
    liste_sprite_poisson : *sprite_template


piranha :
  << : *poisson_template
  predation : 
    est_proie : false 
    est_predateur : true
    proies : 
      - "gupy"
  gestion_faim: 
    faim_max : 100
    faim : 69
    seuil_appetance : 30.0
    valeur_nutritive : 30
  affichage : 
    x : 100
    y : 100
    largeur : 60
    hauteur : 40 
    liste_sprite_poisson : 
      << : *sprite_template
      vers_la_gauche : "images/piranha_vers_la_gauche.png"
      vers_la_droite : "images/piranha_vers_la_droite.png"

crevette : 
  << : *poisson_template
  predation :
    est_proie : false 
    est_predateur : false
  affichage : 
    x : 100
    y : 100
    largeur : 50
    hauteur : 30 
    liste_sprite_poisson : 
      << : *sprite_template
      vers_la_gauche : "images/crevette_vers_la_gauche.png"
      vers_la_droite : "images/crevette_vers_la_droite.png"

tortue : 
  << : *poisson_template
  predation :
    est_proie : false 
    est_predateur : true 
    proies :
      - meduses
  affichage : 
    x : 100
    y : 100
    largeur : 70
    hauteur : 50 
    liste_sprite_poisson : 
      << : *sprite_template
      vers_la_gauche : "images/tortue_vers_la_droite.png"
      vers_la_droite : "images/tortue_vers_la_gauche.png"


sushi : 
  << : *poisson_template
  predation :
    est_proie : false 
    est_predateur : false
  gestion_faim:
    faim_max : 10
    faim : 10
    seuil_appetance : 0
    valeur_nutritive : 0

  affichage : 
    x : 100
    y : 100
    largeur : 70
    hauteur : 50 
    liste_sprite_poisson : 
      << : *sprite_template
      vers_la_gauche : "images/sushi.png"
      vers_la_droite : "images/sushi.png"

meduse : 
  << : *poisson_template
  predation :
    est_proie : false 
    est_predateur : false
  affichage : 
    x : 100
    y : 100
    largeur : 50
    hauteur : 97 
    liste_sprite_poisson : 
      << : *sprite_template
      vers_la_gauche : "images/meduse_vers_la_gauche.png"
      vers_la_droite : "images/meduse_vers_la_droite.png"